version: "3"
services:
   react-app:
    image: react-app
    build: ./frontend
    stdin_open: true
    ports:
      - 3000:3000
    networks:
      - mern-app
    # volumes:
    #   - ./frontend/:/usr/src/app
    #   - /usr/src/app/node_modules
   api-server:
    image: api-server
    build: ./backend
    ports:
      - 5000:5000
    networks:
      - mern-app
    # volumes:
    #   - ./backend/:/usr/src/app
    #   - /usr/src/app/node_modules
    depends_on:
      - mongo
   mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - mern-app
    # volumes:
    #   - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sparsh
      - MONGO_INITDB_ROOT_PASSWORD=sparsh
networks:
    mern-app :
      driver : bridge
# volumes:
#     mongo-data:
#       driver: local